export const ROUTES = {
  home: '/',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  welcome: '/welcome',
  dashboard: '/dashboard',
  place: '/place/:id',
  food: '/food',
  placesHeritage: '/places/heritage',
  placesSpiritual: '/places/spiritual',
  placesArt: '/places/art',
  hiddenGems: '/hidden-gems',
  saved: '/saved',
  visited: '/visited',
  profile: '/profile',
  admin: '/admin',
  adminDashboard: '/admin/dashboard',
  adminPlaces: '/admin/places',
  adminFood: '/admin/food',
  adminHiddenGems: '/admin/hidden-gems',
  adminCategories: '/admin/categories',
  adminImages: '/admin/images',
  adminOpeningHours: '/admin/opening-hours',
  adminUsers: '/admin/users',
} as const
